/* File:     ring_global_sum.c
 *
 * Purpose:  Program that uses MPI to implement a global
 *           sum
 *
 * Input:    None.
 * Output:   Random values generated by processes and sum of random
 *           values on each process.
 *
 * Compile:  mpicc -g -Wall global_sum_rp.c -o sum
 * Run:      sbatch yourJobScript
 *
 * Notes:
 *    1.  The result returned by all the processes should be valid.
 *    2.  The global_sum function uses a ring-pass.
 */
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

const int MAX_CONTRIB = 200;

int global_sum(int my_contrib, int my_rank, int p, MPI_Comm comm);
void print_results(char title[], int value, int my_rank, int p,
                   MPI_Comm comm);

int main(void) {
    int p, my_rank, len;
    int my_contrib;
    int sum;
    char name[MPI_MAX_PROCESSOR_NAME];
    
    // Initialize MPI environment
    MPI_Init(NULL, NULL);
    MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);
    MPI_Comm_size(MPI_COMM_WORLD, &p);
    MPI_Get_processor_name(name, &len);

    /* Generate a random int */
    srandom(my_rank);
    my_contrib = random() % MAX_CONTRIB;

    print_results("Process Values", my_contrib, my_rank, p, MPI_COMM_WORLD);
    
    // Compute the global sum using the ring-pass method
    sum = global_sum(my_contrib, my_rank, p, MPI_COMM_WORLD);

    // Print the total sum as calculated by each process
    print_results("Process Totals", sum, my_rank, p, MPI_COMM_WORLD);

    MPI_Finalize();
    return 0;
}

/*---------------------------------------------------------------
 * Function:  print_results
 * Purpose:   Gather an int from each process onto process 0 and
 *            print the values.
 * In args:
 *    title:  the title of the output
 *    value:  the int contributed by each process
 *    my_rank, p, comm:  the usual MPI values
 */
void print_results(char title[], int value, int my_rank, int p, MPI_Comm comm) {
    int* vals = NULL;
    
    // Only process 0 will gather and print the results
    if (my_rank == 0) {
        vals = malloc(p * sizeof(int));
        // Gather values from all processes
        MPI_Gather(&value, 1, MPI_INT, vals, 1, MPI_INT, 0, comm);
        printf("%s:\n", title);
        for (int q = 0; q < p; q++) {
            printf("Proc %d > %d\n", q, vals[q]);
        }
        printf("\n");
        free(vals);
    } else {
        // Other processes only contribute to the gather
        MPI_Gather(&value, 1, MPI_INT, NULL, 0, MPI_INT, 0, comm);
    }
}



/*-----------------------------------------------------------------
 * Function:    global_sum
 * Purpose:     Compute the global sum of ints stored on the processes
 *
 * Input args:  my_contrib = process's contribution to the global sum
 *              my_rank = process's rank
 *              p = number of processes
 *              comm = communicator
 * Return val:  Sum of each process's my_contrib:  valid on all
 *              processes
 *
 */
int global_sum(int my_contrib, int my_rank, int p, MPI_Comm comm) {
    int sum = my_contrib;
    int temp;

    // Determine the next and previous process in the ring
    int dest = (my_rank + 1) % p;
    int source = (my_rank - 1 + p) % p;

    MPI_Status status;

    // Pass the sum around the ring p-1 times
    for (int i = 0; i < p - 1; i++) {
        // Send the sum to the next process
        MPI_Send(&sum, 1, MPI_INT, dest, 0, comm);
        // Receive the updated sum from the previous process
        MPI_Recv(&temp, 1, MPI_INT, source, 0, comm, &status);
        // Update the sum
        sum += temp;
    }

    return sum;
} /* Global_sum */
