#!/usr/bin/env bash
SCRIPTDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

ORIGIN=$1

if ! $SCRIPTDIR/repo-valid '.'; then
    exit 1
fi

if [ -z "$ORIGIN" ]; then
    echo "Empty origin '$ORIGIN'" >&2
    exit 1
fi

if ! git remote show $ORIGIN 1>/dev/null 2>/dev/null; then
    echo "Remote repository at '$ORIGIN' unknown. Please add with 'git remote add $ORIGIN URL' first." >&2
    exit 1
fi

git fetch "$ORIGIN" '+refs/heads/*:refs/remotes/'"$ORIGIN"'/*'
